rbacApiVersion: rbac.authorization.k8s.io
namespace: alm
catalog_namespace: tectonic-system
alm:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm:master
    pullPolicy: Always
  service:
    internalPort: 8080

catalog:
  replicaCount: 1
  image:
    ref: quay.io/coreos/catalog:master
    pullPolicy: Always
  service:
    internalPort: 8080

servicebroker:
  replicaCount: 1
  image:
    ref: quay.io/coreos/alm-service-broker:master
    pullPolicy: Always
  service:
    internalPort: 8080
    brokerPort: 8005
