rbacApiVersion: rbac.authorization.k8s.io
namespace: operator-lifecycle-manager
catalog_namespace: operator-lifecycle-manager
imagestream: false
debug: false
olm:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm:master
    pullPolicy: Always
  service:
    internalPort: 8080

catalog:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm:master
    pullPolicy: Always
  service:
    internalPort: 8080

package:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm:master
    pullPolicy: Always
  service:
    internalPort: 5443

catalog_sources:
 - rh-operators
 - certified-operators
