rbacApiVersion: rbac.authorization.k8s.io
namespace: operator-lifecycle-manager
# see https://kubernetes.io/docs/concepts/security/pod-security-admission/ for more details
namespace_psa: 
  enforceLevel: baseline
  enforceVersion: latest
  auditLevel: restricted
  auditVersion: latest
  warnLevel: restricted
  warnVersion: latest
catalog_namespace: operator-lifecycle-manager
operator_namespace: operators
# see https://kubernetes.io/docs/concepts/security/pod-security-admission/ for more details
operator_namespace_psa: 
  enforceLevel: baseline
  enforceVersion: latest
minKubeVersion: 1.11.0
writeStatusName: '""'
imagestream: false
debug: false
installType: upstream
catalogGrpcPodPort: 50051

olm:
  replicaCount: 1
  image:
    ref: quay.io/operator-framework/olm:master
    pullPolicy: Always
  service:
    internalPort: 8080
    externalPort: metrics
  # tlsSecret: olm-operator-serving-cert
  # clientCASecret: pprof-serving-cert
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
     cpu: 10m
     memory: 160Mi

catalog:
  setWorkloadUserID: true
  replicaCount: 1
  commandArgs: --configmapServerImage=quay.io/operator-framework/configmap-operator-registry:latest
  opmImageArgs: --opmImage=quay.io/operator-framework/opm:latest
  image:
    ref: quay.io/operator-framework/olm:master
    pullPolicy: Always
  service:
    internalPort: 8080
    externalPort: metrics
  # tlsSecret: catalog-operator-serving-cert
  # clientCASecret: pprof-serving-cert
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
     cpu: 10m
     memory: 80Mi

package:
  replicaCount: 2
  maxUnavailable: 1
  maxSurge: 1
  image:
    ref: quay.io/operator-framework/olm:master
    pullPolicy: Always
  service:
    internalPort: 5443
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
     cpu: 10m
     memory: 50Mi

monitoring:
  enabled: false
  namespace: monitoring

networkPolicy:
  dns:
    ports:
      - protocol: TCP
        port: 53
      - protocol: UDP
        port: 53
  kubeAPIServer:
    ports:
      - protocol: TCP
        port: 6443
  metrics:
    ports:
      - protocol: TCP
        port: metrics
