apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-operator
  namespace: {{ .Values.namespace }}
  labels:
    app: catalog-operator
spec:
  strategy:
    type: RollingUpdate
  replicas: {{ .Values.catalog.replicaCount }}
  selector:
    matchLabels:
      app: catalog-operator
  template:
    metadata:
      labels:
        app: catalog-operator
    spec:
      serviceAccountName: olm-operator-serviceaccount
      containers:
        - name: catalog-operator
          command:
          - /bin/catalog
          args:
          {{- if .Values.watchedNamespaces }}
          - -watchedNamespaces
          - {{ .Values.watchedNamespaces }}
          {{- end }}
          - '-namespace'
          - {{ .Values.catalog_namespace }}
          {{- if .Values.debug }}
          - '-debug'
          {{- end }}
          {{- if .Values.catalog.commandArgs }}
          - {{ .Values.catalog.commandArgs }}
          {{- end }}
          image: {{ .Values.catalog.image.ref }}
          imagePullPolicy: {{ .Values.catalog.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.catalog.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.catalog.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.catalog.service.internalPort }}
          {{- if .Values.catalog.resources }}
          resources:
{{ toYaml .Values.catalog.resources | indent 12 }}
          {{- end}}
    {{- if .Values.catalog.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.catalog.nodeSelector | indent 8 }}
    {{- end }}
      imagePullSecrets:
        - name: coreos-pull-secret
