#! validate-crd: ./deploy/chart/templates/06-catalogsource.crd.yaml
#! parse-kind: CatalogSource
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: olm-operators
  namespace: {{ .Values.namespace }}
spec:
  sourceType: internal
  configMap: olm-operators
  displayName: OLM Operators
  publisher: Red Hat
