#! validate-crd: ./deploy/chart/templates/04-subscription.crd.yaml
#! parse-kind: Subscription
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: packageserver
  namespace: {{ .Values.namespace }}
spec:
  source: olm-operators
  name: packageserver
  channel: alpha
