{{ if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: olm-alert-rules
  namespace: {{ .Values.namespace }}
  labels:
    prometheus: alert-rules
    role: alert-rules
spec:
  groups:
  - name: olm.csv_abnormal.rules
    rules:
      - alert: CsvAbnormalFailedOver2Min
        expr: csv_abnormal{phase=~"^Failed$"}
        for: 2m
        labels:
          severity: warning
          namespace: "{{ "{{ $labels.namespace }}" }}"
        annotations:
          message: Failed to install Operator {{ printf "{{ $labels.name }}"  }} version {{ printf "{{ $labels.version }}"  }}. Reason-{{ printf "{{ $labels.reason }}" }}
      - alert: CsvAbnormalOver30Min
        expr: csv_abnormal{phase=~"(^Replacing$|^Pending$|^Deleting$|^Unknown$)"}
        for: 30m
        labels:
          severity: warning
          namespace: "{{ "{{ $labels.namespace }}" }}"
        annotations:
          message: Failed to install Operator {{ printf "{{ $labels.name }}"  }} version {{ printf "{{ $labels.version }}"  }}. Phase-{{ printf "{{ $labels.phase }}" }} Reason-{{ printf "{{ $labels.reason }}" }}
  - name: olm.installplan.rules
    rules:
    - alert: InstallPlanStepAppliedWithWarnings
      expr: sum(increase(installplan_warnings_total[5m])) > 0
      labels:
        severity: warning
      annotations:
        message: The API server returned a warning during installation or upgrade of an operator. An Event with reason "AppliedWithWarnings" has been created with complete details, including a reference to the InstallPlan step that generated the warning.
{{ end }}
