apiVersion: {{ .Values.rbacApiVersion }}/v1
kind: ClusterRoleBinding
metadata:
  name: olm-operator-binding-{{ .Values.namespace }}
  labels:
    tectonic-operators.coreos.com/managed-by: tectonic-x-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: {{ .Values.namespace }}
