#! validate-crd: ../../deploy/chart/templates/05-catalogsource.crd.yaml
#! parse-kind: CatalogSource
apiVersion: app.coreos.com/v1alpha1
kind: CatalogSource-v1
metadata:
  name: tectonic-alm-components-catalog
  namespace: {{ .Values.catalog_namespace }}
  annotations:
    tectonic-operators.coreos.com/upgrade-strategy: 'DeleteAndRecreate'
spec:
  name: tectonic-components
  sourceType: internal
  configMap: tectonic-components
  secrets:
  - coreos-pull-secret
  displayName: Tectonic Cluster Components
  publisher: CoreOS, Inc.
