{{ if .Values.servicebroker }}
apiVersion: v1
kind: Secret
metadata:
  name: almservicebroker-client
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: alm-operator-serviceaccount
type: kubernetes.io/service-account-token
{{ end }}
