{{- $ca := genCA "package-server-ca" 3650 -}}
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.packages.apps.redhat.com
spec:
  caBundle: {{ b64enc $ca.Cert }}
  group: packages.apps.redhat.com
  groupPriorityMinimum: 2000
  versionPriority: 15
  service:
    name: package-server
    namespace: {{ .Values.namespace }}
  version: v1alpha1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packagemanifest:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: packagemanifest-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: packagemanifest-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: package-apiserver-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aggregated-apiserver-clusterrole
subjects:
- kind: ServiceAccount
  name: olm-operator-serviceaccount
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: package-server-certs
  namespace: {{ .Values.namespace }}
  labels:
    app: package-server
data:
{{- $altNames := list ( printf "package-server.%s" .Values.namespace ) ( printf "package-server.%s.svc" .Values.namespace ) -}}
{{- $cert := genSignedCert "package-server" nil $altNames 365 $ca }}
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: package-server
  namespace: {{ .Values.namespace }}
  labels:
    app: package-server
spec:
  strategy:
    type: RollingUpdate
  replicas: {{ .Values.package.replicaCount }}
  selector:
    matchLabels:
      app: package-server
  template:
    metadata:
      labels:
        app: package-server
    spec:
      serviceAccountName: olm-operator-serviceaccount
      containers:
      - name: package-server
        command:
        - /bin/package-server
        - -v=4
        {{- if .Values.watchedNamespaces }}
        - --watched-namespaces
        - {{ .Values.watchedNamespaces }}
        {{- end }}
        - --global-namespace
        - {{ .Values.namespace }}
        - --debug
        {{- if .Values.package.commandArgs }}
        - {{ .Values.package.commandArgs }}
        {{- end }}
        image: {{ .Values.package.image.ref }}
        imagePullPolicy: {{ .Values.package.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.package.service.internalPort }}
        volumeMounts:
        - name: certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: {{ .Values.package.service.internalPort }}
        readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: {{ .Values.package.service.internalPort }}
      volumes:
      - name: certs
        secret:
          secretName: package-server-certs
          items:
          - key: tls.crt
            path: apiserver.crt
          - key: tls.key
            path: apiserver.key
      imagePullSecrets:
        - name: coreos-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: package-server
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: package-server
