---
# Source: olm/templates/0000_90_olm_01-prometheus-rule.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: olm-alert-rules
  namespace: openshift-operator-lifecycle-manager
  labels:
    prometheus: alert-rules
    role: alert-rules
spec:
  groups:
    - name: olm.failing_operators.rules
      rules:
        - alert: FailingOperator
          annotations:
            message: Failed to install Operator {{ $labels.name }} version {{ $labels.version }}. Reason-{{ $labels.reason }}
          expr: csv_abnormal{phase="Failed"}
          labels:
            severity: warning
