---
# Source: olm/templates/0000_50_olm_99-operatorstatus.yaml
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: operator-lifecycle-manager
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
---
# Source: olm/templates/0000_50_olm_99-operatorstatus.yaml
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: operator-lifecycle-manager-catalog
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
---
# Source: olm/templates/0000_50_olm_99-operatorstatus.yaml
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: operator-lifecycle-manager-packageserver
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
