---
# Source: alm/templates/11-tectoniccomponents.catalogsource.yaml
#! validate-crd: ../../deploy/chart/templates/05-catalogsource.crd.yaml
#! parse-kind: CatalogSource
apiVersion: app.coreos.com/v1alpha1
kind: CatalogSource-v1
metadata:
  name: tectonic-components
  namespace: tectonic-system
  annotations:
    tectonic-operators.coreos.com/upgrade-strategy: 'DeleteAndRecreate'
spec:
  name: tectonic-components
  sourceType: internal
  configMap: tectonic-components
  displayName: Tectonic Cluster Components
  publisher: CoreOS, Inc.

