apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: olm-alert-rules
  namespace: openshift-operator-lifecycle-manager
  labels:
    prometheus: alert-rules
    role: alert-rules
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  groups:
    - name: olm.failing_operators.rules
      rules:
        - alert: FailingOperator
          annotations:
            message: Failed to install Operator {{ $labels.name }} version {{ $labels.version }}. Reason-{{ $labels.reason }}
          expr: csv_abnormal{phase="Failed"}
          labels:
            severity: warning
