apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: operator-lifecycle-manager
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
---
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: operator-lifecycle-manager-catalog
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
---
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: operator-lifecycle-manager-packageserver
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
