apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operator-lifecycle-manager
  
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/scc: "anyuid"
    openshift.io/cluster-monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators
  
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/scc: "anyuid"
