##---
# Source: olm/templates/0000_30_16-operatorgroup-default.yaml
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: global-operators
  namespace: openshift-operators
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: olm-operators
  namespace: openshift-operator-lifecycle-manager
spec:
  targetNamespaces:
    - openshift-operator-lifecycle-manager
