installType: upstream
rbacApiVersion: rbac.authorization.k8s.io
namespace: olm
catalog_namespace: olm
operator_namespace: operators
imagestream: false
writeStatusName: '""'
writePackageServerStatusName: ""
olm:
  replicaCount: 1
  image:
    ref: quay.io/operator-framework/olm@sha256:0d15ffb5d10a176ef6e831d7865f98d51255ea5b0d16403618c94a004d049373
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
catalog:
  replicaCount: 1
  image:
    ref: quay.io/operator-framework/olm@sha256:0d15ffb5d10a176ef6e831d7865f98d51255ea5b0d16403618c94a004d049373
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
package:
  replicaCount: 2
  image:
    ref: quay.io/operator-framework/olm@sha256:0d15ffb5d10a176ef6e831d7865f98d51255ea5b0d16403618c94a004d049373
    pullPolicy: Always
  service:
    internalPort: 5443
  securityContext:
    runAsUser: 1000
catalog_sources:
- rh-operators
