#! package-manifest: deploy/chart/catalog_resources/certified-operators/couchbase.1.0.0.clusterserviceversion.yaml
packageName: couchbase-enterprise
channels:
- name: preview
  currentCSV: couchbase-operator.v1.0.0
