---
# Source: olm/templates/0000_50_olm_13-operatorgroup-default.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: global-operators
  namespace: openshift-operators
---
# Source: olm/templates/0000_50_olm_13-operatorgroup-default.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: olm-operators
  namespace: openshift-operator-lifecycle-manager
spec:
  targetNamespaces:
    - openshift-operator-lifecycle-manager
