#! package-manifest: ./deploy/chart/catalog_resources/rh-operators/clusterloggings.v0.0.1.clusterserviceversion.yaml
packageName: clusterLogging
channels:
- name: preview
  currentCSV: clusterlogging.v0.0.1
