#! validate-crd: deploy/chart/templates/0000_30_02-clusterserviceversion.crd.yaml
#! parse-kind: ClusterServiceVersion
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: federationv2.v0.0.2
  namespace: placeholder
spec:
  displayName: FederationV2
  description: |
    Kubernetes Federation V2 namespace-scoped installation
  version: 0.0.2
  maturity: alpha
  provider:
    name: Red Hat, Inc
  labels:
    alm-owner-federationv2: federationv2
    alm-status-descriptors: federationv2.v0.0.2
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: true
  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: federation-controller-manager
        rules:
        - apiGroups:
          - clusterregistry.k8s.io
          resources:
          - clusters
          verbs:
          - "*"
        - apiGroups:
          - core.federation.k8s.io
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - multiclusterdns.federation.k8s.io
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - scheduling.federation.k8s.io
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - "*"
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - "*"
      # TODO(font): use statefulset
      deployments:
      - name: federation-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: federation-controller-manager
          template:
            metadata:
              labels:
                app: federation-controller-manager
            spec:
              containers:
                - name: controller-manager
                  image: quay.io/kubernetes-multicluster/federation-v2:v0.0.2-rc.1
                  resources:
                    limits:
                      cpu: 100m
                      memory: 128Mi
                    requests:
                      cpu: 100m
                      memory: 64Mi
                  command:
                    - /root/controller-manager
                  args:
                    - --federation-namespace=$(FEDERATION_NAMESPACE)
                    - --install-crds=false
                    - --limited-scope=true
                    - --registry-namespace=$(CLUSTER_REGISTRY_NAMESPACE)
                  imagePullPolicy: Always
                  env:
                  - name: FEDERATION_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  - name: CLUSTER_REGISTRY_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
              restartPolicy: Always
              terminationGracePeriodSeconds: 5
              serviceAccountName: federation-controller-manager
              serviceAccount: federation-controller-manager
  customresourcedefinitions:
    owned:
        # TODO(font): Move Cluster CRD to required once OLM supports CSVs
        # without a deployment.
      - description: Represents an instance of a Cluster Registry
        displayName: Cluster Registry Application
        kind: Cluster
        name: clusters.clusterregistry.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedCluster resource
        displayName: FederatedCluster Resource
        kind: FederatedCluster
        name: federatedclusters.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedConfigMap resource
        displayName: FederatedConfigMap Resource
        kind: FederatedConfigMap
        name: federatedconfigmaps.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedConfigMapOverride resource
        displayName: FederatedConfigMapOverride Resource
        kind: FederatedConfigMapOverride
        name: federatedconfigmapoverrides.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedConfigMapPlacement resource
        displayName: FederatedConfigMapPlacement Resource
        kind: FederatedConfigMapPlacement
        name: federatedconfigmapplacements.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedDeployment resource
        displayName: FederatedDeployment Resource
        kind: FederatedDeployment
        name: federateddeployments.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedDeploymentOverride resource
        displayName: FederatedDeploymentOverride Resource
        kind: FederatedDeploymentOverride
        name: federateddeploymentoverrides.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedDeploymentPlacement resource
        displayName: FederatedDeploymentPlacement Resource
        kind: FederatedDeploymentPlacement
        name: federateddeploymentplacements.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedIngress resource
        displayName: FederatedIngress Resource
        kind: FederatedIngress
        name: federatedingresses.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedIngressPlacement resource
        displayName: FederatedIngressPlacement Resource
        kind: FederatedIngressPlacement
        name: federatedingressplacements.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedJob resource
        displayName: FederatedJob Resource
        kind: FederatedJob
        name: federatedjobs.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedJobOverride resource
        displayName: FederatedJobOverride Resource
        kind: FederatedJobOverride
        name: federatedjoboverrides.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedJobPlacement resource
        displayName: FederatedJobPlacement Resource
        kind: FederatedJobPlacement
        name: federatedjobplacements.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedNamespacePlacement resource
        displayName: FederatedNamespacePlacement Resource
        kind: FederatedNamespacePlacement
        name: federatednamespaceplacements.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedReplicaSet resource
        displayName: FederatedReplicaSet Resource
        kind: FederatedReplicaSet
        name: federatedreplicasets.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedReplicaSetOverride resource
        displayName: FederatedReplicaSetOverride Resource
        kind: FederatedReplicaSetOverride
        name: federatedreplicasetoverrides.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedReplicaSetPlacement resource
        displayName: FederatedReplicaSetPlacement Resource
        kind: FederatedReplicaSetPlacement
        name: federatedreplicasetplacements.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedSecret resource
        displayName: FederatedSecret Resource
        kind: FederatedSecret
        name: federatedsecrets.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedSecretOverride resource
        displayName: FederatedSecretOverride Resource
        kind: FederatedSecretOverride
        name: federatedsecretoverrides.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedSecretPlacement resource
        displayName: FederatedSecretPlacement Resource
        kind: FederatedSecretPlacement
        name: federatedsecretplacements.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedService resource
        displayName: FederatedService Resource
        kind: FederatedService
        name: federatedservices.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedServiceAccount resource
        displayName: FederatedServiceAccount Resource
        kind: FederatedServiceAccount
        name: federatedserviceaccounts.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedServiceAccountPlacement resource
        displayName: FederatedServiceAccountPlacement Resource
        kind: FederatedServiceAccountPlacement
        name: federatedserviceaccountplacements.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederatedServicePlacement resource
        displayName: FederatedServicePlacement Resource
        kind: FederatedServicePlacement
        name: federatedserviceplacements.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a FederationV2 sync controller
        displayName: FederationV2 Push Reconciler Application
        kind: FederatedTypeConfig
        name: federatedtypeconfigs.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a PropagatedVersion resource
        displayName: PropagatedVersion Resource
        kind: PropagatedVersion
        name: propagatedversions.core.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a DNSEndpoint resource
        displayName: DNSEndpoint Resource
        kind: DNSEndpoint
        name: dnsendpoints.multiclusterdns.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a MultiClusterIngressDNSRecord resource
        displayName: MultiClusterIngressDNSRecord Resource
        kind: MultiClusterIngressDNSRecord
        name: multiclusteringressdnsrecords.multiclusterdns.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a MultiClusterServiceDNSRecord resource
        displayName: MultiClusterServiceDNSRecord Resource
        kind: MultiClusterServiceDNSRecord
        name: multiclusterservicednsrecords.multiclusterdns.federation.k8s.io
        version: v1alpha1
      - description: Represents an instance of a ReplicaSchedulingPreference resource
        displayName: ReplicaSchedulingPreference Resource
        kind: ReplicaSchedulingPreference
        name: replicaschedulingpreferences.scheduling.federation.k8s.io
        version: v1alpha1
