apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: storagelocations.metering.openshift.io
  annotations:
    catalog.app.coreos.com/displayName: "Metering storage location"
    catalog.app.coreos.com/description: "Represents a configurable storage location for Metering to store metering and report data"
spec:
  group: metering.openshift.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: storagelocations
    kind: StorageLocation
