rbacApiVersion: authorization.openshift.io
namespace: local
watchedNamespaces: local
catalog_namespace: local
alm:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm:local
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080

catalog:
  replicaCount: 1
  image:
    ref: quay.io/coreos/catalog:local
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080

servicebroker:
  replicaCount: 1
  image:
    ref: quay.io/coreos/alm-service-broker:local
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
    brokerPort: 8005

catalog_sources:
 - tectonic-ocs
 - upstream-components
