rbacApiVersion: rbac.authorization.k8s.io
namespace: local
watchedNamespaces: local
catalog_namespace: local
operator_namespace: local-operators
debug: true

olm:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm:local
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080

catalog:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm:local
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080

package:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm:local
    pullPolicy: IfNotPresent
  service:
    internalPort: 5443

catalog_sources:
 - rh-operators
