name: e2e
on:
  pull_request:
    paths:
    - '**'
    - '!doc/contributors/**'
    - '!doc/design/**'
  schedule:
  - cron: '0 0 * * *' # daily to pick up releases
jobs:
  run-local-kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '~1.16'
    - name: Install kind
      run: |
        curl -sLo kind "$(curl -sL https://api.github.com/repos/kubernetes-sigs/kind/releases/latest | jq -r '[.assets[] | select(.name == "kind-linux-amd64")] | first | .browser_download_url')"
        chmod +x kind
        sudo mv kind /bin/
    - name: Create kind cluster
      run: |
        kind create cluster
        kind export kubeconfig
    - name: Run e2e tests
      run: make run-local
