name: e2e-tests-periodic-flak-analysis
on:
  schedule:
    - cron: '0 0 12 * * SUN'
jobs:
  flak-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: ${{ github.workspace }}/bin/artifacts/
    # - run: make e2e-test-report-analysis
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ${{ github.workspace }}/bin/artifacts/
