##---
# Source: olm/templates/0000_50_olm_02-services.yaml

apiVersion: v1
kind: Service
metadata:
  name: olm-operator-metrics
  namespace: openshift-operator-lifecycle-manager
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: olm-operator-serving-cert
  labels:
    app: olm-operator
spec:
  type: ClusterIP
  ports:
  - name: https-metrics
    port: 8081
    protocol: TCP
    targetPort: metrics
  selector:
    app: olm-operator
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-operator-metrics
  namespace: openshift-operator-lifecycle-manager
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: catalog-operator-serving-cert
  labels:
    app: catalog-operator
spec:
  type: ClusterIP
  ports:
  - name: https-metrics
    port: 8081
    protocol: TCP
    targetPort: metrics
  selector:
    app: catalog-operator

